name: await_route
description: Utility to await route transitions.
version: 0.0.1
homepage: https://github.com/volskaya/stasha.flutter/tree/main/packages/await_route

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
